version: "3.9"

x-jwt: &jwt
  JWT_SECRET: "minha_chave_secreta_super_segura"

services:
  gateway:
    build: ./gateway
    ports: ["5000:5000"]
    environment:
      <<: *jwt
      USERS_URL: https://users:5001
      PRODUCTS_URL: https://products:5002
      REPLICA_URL: https://products-replica:5012
      ORDERS_URL: https://orders:5003
    volumes: ["./certs:/app/certs"]
    depends_on: [users, products, products-replica, orders]

  users:
    build: ./users
    ports: ["5001:5001"]
    environment: { <<: *jwt }
    volumes:
      - "./users/data:/app/data"
      - "./certs:/app/certs"
    command: uvicorn main:app --host 0.0.0.0 --port 5001 --ssl-keyfile /app/certs/key.pem --ssl-certfile /app/certs/cert.pem

  products:
    build: ./products
    ports: ["5002:5002"]
    environment:
      <<: *jwt
      REPLICA_ID: primary
    volumes:
      - "./products/data:/app/data"
      - "./certs:/app/certs"
    command: uvicorn main:app --host 0.0.0.0 --port 5002 --ssl-keyfile /app/certs/key.pem --ssl-certfile /app/certs/cert.pem

  products-replica:
    build: ./products
    ports: ["5012:5012"]
    environment:
      <<: *jwt
      REPLICA_ID: replica
    volumes:
      - "./products/data:/app/data"
      - "./certs:/app/certs"
    command: uvicorn main:app --host 0.0.0.0 --port 5012 --ssl-keyfile /app/certs/key.pem --ssl-certfile /app/certs/cert.pem

  orders:
    build: ./orders
    ports: ["5003:5003"]
    environment: { <<: *jwt }
    volumes:
      - "./orders/data:/app/data"
      - "./certs:/app/certs"
    command: uvicorn main:app --host 0.0.0.0 --port 5003 --ssl-keyfile /app/certs/key.pem --ssl-certfile /app/certs/cert.pem